/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlugininstallRouteImport } from './routes/plugininstall'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FavoritesRouteRouteImport } from './routes/favorites/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists.$playlistId'
import { Route as FavoritesVideosRouteImport } from './routes/favorites/videos'
import { Route as FavoritesPlaylistsRouteImport } from './routes/favorites/playlists'
import { Route as FavoritesChannelsRouteImport } from './routes/favorites/channels'
import { Route as PluginsPluginIdIndexRouteImport } from './routes/plugins/$pluginId.index'
import { Route as PluginsPluginIdOptionsRouteImport } from './routes/plugins/$pluginId/options'
import { Route as PluginsPluginIdPlaylistsIndexRouteImport } from './routes/plugins/$pluginId/playlists.index'
import { Route as PluginsPluginIdChannelsIndexRouteImport } from './routes/plugins/$pluginId/channels.index'
import { Route as PluginsPluginIdVideosApiIdRouteImport } from './routes/plugins/$pluginId/videos.$apiId'
import { Route as PluginsPluginIdPlaylistsApiIdRouteImport } from './routes/plugins/$pluginId/playlists.$apiId'
import { Route as PluginsPluginIdChannelsApiIdIndexRouteImport } from './routes/plugins/$pluginId/channels.$apiId.index'
import { Route as PluginsPluginIdChannelsApiIdLiveRouteImport } from './routes/plugins/$pluginId/channels.$apiId.live'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlugininstallRoute = PlugininstallRouteImport.update({
  id: '/plugininstall',
  path: '/plugininstall',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRouteRoute = FavoritesRouteRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesVideosRoute = FavoritesVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => FavoritesRouteRoute,
} as any)
const FavoritesPlaylistsRoute = FavoritesPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => FavoritesRouteRoute,
} as any)
const FavoritesChannelsRoute = FavoritesChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => FavoritesRouteRoute,
} as any)
const PluginsPluginIdIndexRoute = PluginsPluginIdIndexRouteImport.update({
  id: '/plugins/$pluginId/',
  path: '/plugins/$pluginId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdOptionsRoute = PluginsPluginIdOptionsRouteImport.update({
  id: '/plugins/$pluginId/options',
  path: '/plugins/$pluginId/options',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdPlaylistsIndexRoute =
  PluginsPluginIdPlaylistsIndexRouteImport.update({
    id: '/plugins/$pluginId/playlists/',
    path: '/plugins/$pluginId/playlists/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdChannelsIndexRoute =
  PluginsPluginIdChannelsIndexRouteImport.update({
    id: '/plugins/$pluginId/channels/',
    path: '/plugins/$pluginId/channels/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdVideosApiIdRoute =
  PluginsPluginIdVideosApiIdRouteImport.update({
    id: '/plugins/$pluginId/videos/$apiId',
    path: '/plugins/$pluginId/videos/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdPlaylistsApiIdRoute =
  PluginsPluginIdPlaylistsApiIdRouteImport.update({
    id: '/plugins/$pluginId/playlists/$apiId',
    path: '/plugins/$pluginId/playlists/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdChannelsApiIdIndexRoute =
  PluginsPluginIdChannelsApiIdIndexRouteImport.update({
    id: '/plugins/$pluginId/channels/$apiId/',
    path: '/plugins/$pluginId/channels/$apiId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdChannelsApiIdLiveRoute =
  PluginsPluginIdChannelsApiIdLiveRouteImport.update({
    id: '/plugins/$pluginId/channels/$apiId/live',
    path: '/plugins/$pluginId/channels/$apiId/live',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/channels': typeof FavoritesChannelsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/videos': typeof FavoritesVideosRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/videos/$apiId': typeof PluginsPluginIdVideosApiIdRoute
  '/plugins/$pluginId/channels/': typeof PluginsPluginIdChannelsIndexRoute
  '/plugins/$pluginId/playlists/': typeof PluginsPluginIdPlaylistsIndexRoute
  '/plugins/$pluginId/channels/$apiId/live': typeof PluginsPluginIdChannelsApiIdLiveRoute
  '/plugins/$pluginId/channels/$apiId/': typeof PluginsPluginIdChannelsApiIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/channels': typeof FavoritesChannelsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/videos': typeof FavoritesVideosRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/videos/$apiId': typeof PluginsPluginIdVideosApiIdRoute
  '/plugins/$pluginId/channels': typeof PluginsPluginIdChannelsIndexRoute
  '/plugins/$pluginId/playlists': typeof PluginsPluginIdPlaylistsIndexRoute
  '/plugins/$pluginId/channels/$apiId/live': typeof PluginsPluginIdChannelsApiIdLiveRoute
  '/plugins/$pluginId/channels/$apiId': typeof PluginsPluginIdChannelsApiIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/channels': typeof FavoritesChannelsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/videos': typeof FavoritesVideosRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/videos/$apiId': typeof PluginsPluginIdVideosApiIdRoute
  '/plugins/$pluginId/channels/': typeof PluginsPluginIdChannelsIndexRoute
  '/plugins/$pluginId/playlists/': typeof PluginsPluginIdPlaylistsIndexRoute
  '/plugins/$pluginId/channels/$apiId/live': typeof PluginsPluginIdChannelsApiIdLiveRoute
  '/plugins/$pluginId/channels/$apiId/': typeof PluginsPluginIdChannelsApiIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/channels'
    | '/favorites/playlists'
    | '/favorites/videos'
    | '/playlists/$playlistId'
    | '/playlists/'
    | '/plugins/'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId/'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/videos/$apiId'
    | '/plugins/$pluginId/channels/'
    | '/plugins/$pluginId/playlists/'
    | '/plugins/$pluginId/channels/$apiId/live'
    | '/plugins/$pluginId/channels/$apiId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/channels'
    | '/favorites/playlists'
    | '/favorites/videos'
    | '/playlists/$playlistId'
    | '/playlists'
    | '/plugins'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/videos/$apiId'
    | '/plugins/$pluginId/channels'
    | '/plugins/$pluginId/playlists'
    | '/plugins/$pluginId/channels/$apiId/live'
    | '/plugins/$pluginId/channels/$apiId'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/channels'
    | '/favorites/playlists'
    | '/favorites/videos'
    | '/playlists/$playlistId'
    | '/playlists/'
    | '/plugins/'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId/'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/videos/$apiId'
    | '/plugins/$pluginId/channels/'
    | '/plugins/$pluginId/playlists/'
    | '/plugins/$pluginId/channels/$apiId/live'
    | '/plugins/$pluginId/channels/$apiId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRouteRoute: typeof FavoritesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  PlugininstallRoute: typeof PlugininstallRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsPluginIdOptionsRoute: typeof PluginsPluginIdOptionsRoute
  PluginsPluginIdIndexRoute: typeof PluginsPluginIdIndexRoute
  PluginsPluginIdPlaylistsApiIdRoute: typeof PluginsPluginIdPlaylistsApiIdRoute
  PluginsPluginIdVideosApiIdRoute: typeof PluginsPluginIdVideosApiIdRoute
  PluginsPluginIdChannelsIndexRoute: typeof PluginsPluginIdChannelsIndexRoute
  PluginsPluginIdPlaylistsIndexRoute: typeof PluginsPluginIdPlaylistsIndexRoute
  PluginsPluginIdChannelsApiIdLiveRoute: typeof PluginsPluginIdChannelsApiIdLiveRoute
  PluginsPluginIdChannelsApiIdIndexRoute: typeof PluginsPluginIdChannelsApiIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugininstall': {
      id: '/plugininstall'
      path: '/plugininstall'
      fullPath: '/plugininstall'
      preLoaderRoute: typeof PlugininstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/videos': {
      id: '/favorites/videos'
      path: '/videos'
      fullPath: '/favorites/videos'
      preLoaderRoute: typeof FavoritesVideosRouteImport
      parentRoute: typeof FavoritesRouteRoute
    }
    '/favorites/playlists': {
      id: '/favorites/playlists'
      path: '/playlists'
      fullPath: '/favorites/playlists'
      preLoaderRoute: typeof FavoritesPlaylistsRouteImport
      parentRoute: typeof FavoritesRouteRoute
    }
    '/favorites/channels': {
      id: '/favorites/channels'
      path: '/channels'
      fullPath: '/favorites/channels'
      preLoaderRoute: typeof FavoritesChannelsRouteImport
      parentRoute: typeof FavoritesRouteRoute
    }
    '/plugins/$pluginId/': {
      id: '/plugins/$pluginId/'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId/'
      preLoaderRoute: typeof PluginsPluginIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/options': {
      id: '/plugins/$pluginId/options'
      path: '/plugins/$pluginId/options'
      fullPath: '/plugins/$pluginId/options'
      preLoaderRoute: typeof PluginsPluginIdOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/playlists/': {
      id: '/plugins/$pluginId/playlists/'
      path: '/plugins/$pluginId/playlists'
      fullPath: '/plugins/$pluginId/playlists/'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/channels/': {
      id: '/plugins/$pluginId/channels/'
      path: '/plugins/$pluginId/channels'
      fullPath: '/plugins/$pluginId/channels/'
      preLoaderRoute: typeof PluginsPluginIdChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/videos/$apiId': {
      id: '/plugins/$pluginId/videos/$apiId'
      path: '/plugins/$pluginId/videos/$apiId'
      fullPath: '/plugins/$pluginId/videos/$apiId'
      preLoaderRoute: typeof PluginsPluginIdVideosApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/playlists/$apiId': {
      id: '/plugins/$pluginId/playlists/$apiId'
      path: '/plugins/$pluginId/playlists/$apiId'
      fullPath: '/plugins/$pluginId/playlists/$apiId'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/channels/$apiId/': {
      id: '/plugins/$pluginId/channels/$apiId/'
      path: '/plugins/$pluginId/channels/$apiId'
      fullPath: '/plugins/$pluginId/channels/$apiId/'
      preLoaderRoute: typeof PluginsPluginIdChannelsApiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/channels/$apiId/live': {
      id: '/plugins/$pluginId/channels/$apiId/live'
      path: '/plugins/$pluginId/channels/$apiId/live'
      fullPath: '/plugins/$pluginId/channels/$apiId/live'
      preLoaderRoute: typeof PluginsPluginIdChannelsApiIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FavoritesRouteRouteChildren {
  FavoritesChannelsRoute: typeof FavoritesChannelsRoute
  FavoritesPlaylistsRoute: typeof FavoritesPlaylistsRoute
  FavoritesVideosRoute: typeof FavoritesVideosRoute
}

const FavoritesRouteRouteChildren: FavoritesRouteRouteChildren = {
  FavoritesChannelsRoute: FavoritesChannelsRoute,
  FavoritesPlaylistsRoute: FavoritesPlaylistsRoute,
  FavoritesVideosRoute: FavoritesVideosRoute,
}

const FavoritesRouteRouteWithChildren = FavoritesRouteRoute._addFileChildren(
  FavoritesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRouteRoute: FavoritesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  PlugininstallRoute: PlugininstallRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsPluginIdOptionsRoute: PluginsPluginIdOptionsRoute,
  PluginsPluginIdIndexRoute: PluginsPluginIdIndexRoute,
  PluginsPluginIdPlaylistsApiIdRoute: PluginsPluginIdPlaylistsApiIdRoute,
  PluginsPluginIdVideosApiIdRoute: PluginsPluginIdVideosApiIdRoute,
  PluginsPluginIdChannelsIndexRoute: PluginsPluginIdChannelsIndexRoute,
  PluginsPluginIdPlaylistsIndexRoute: PluginsPluginIdPlaylistsIndexRoute,
  PluginsPluginIdChannelsApiIdLiveRoute: PluginsPluginIdChannelsApiIdLiveRoute,
  PluginsPluginIdChannelsApiIdIndexRoute:
    PluginsPluginIdChannelsApiIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
