/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as SearchImport } from './routes/search'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as PlugininstallImport } from './routes/plugininstall'
import { Route as DonateImport } from './routes/donate'
import { Route as AboutImport } from './routes/about'
import { Route as FavoritesRouteImport } from './routes/favorites/route'
import { Route as IndexImport } from './routes/index'
import { Route as PluginsIndexImport } from './routes/plugins.index'
import { Route as PlaylistsIndexImport } from './routes/playlists.index'
import { Route as PlaylistsPlaylistIdImport } from './routes/playlists.$playlistId'
import { Route as FavoritesVideosImport } from './routes/favorites/videos'
import { Route as FavoritesPlaylistsImport } from './routes/favorites/playlists'
import { Route as FavoritesChannelsImport } from './routes/favorites/channels'
import { Route as PluginsPluginIdIndexImport } from './routes/plugins/$pluginId.index'
import { Route as PluginsPluginIdOptionsImport } from './routes/plugins/$pluginId/options'
import { Route as PluginsPluginIdPlaylistsIndexImport } from './routes/plugins/$pluginId/playlists.index'
import { Route as PluginsPluginIdChannelsIndexImport } from './routes/plugins/$pluginId/channels.index'
import { Route as PluginsPluginIdVideosApiIdImport } from './routes/plugins/$pluginId/videos.$apiId'
import { Route as PluginsPluginIdPlaylistsApiIdImport } from './routes/plugins/$pluginId/playlists.$apiId'
import { Route as PluginsPluginIdChannelsApiIdIndexImport } from './routes/plugins/$pluginId/channels.$apiId.index'
import { Route as PluginsPluginIdChannelsApiIdLiveImport } from './routes/plugins/$pluginId/channels.$apiId.live'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const PlugininstallRoute = PlugininstallImport.update({
  id: '/plugininstall',
  path: '/plugininstall',
  getParentRoute: () => rootRoute,
} as any)

const DonateRoute = DonateImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesRouteRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PluginsIndexRoute = PluginsIndexImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsIndexRoute = PlaylistsIndexImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesVideosRoute = FavoritesVideosImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const FavoritesPlaylistsRoute = FavoritesPlaylistsImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const FavoritesChannelsRoute = FavoritesChannelsImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const PluginsPluginIdIndexRoute = PluginsPluginIdIndexImport.update({
  id: '/plugins/$pluginId/',
  path: '/plugins/$pluginId/',
  getParentRoute: () => rootRoute,
} as any)

const PluginsPluginIdOptionsRoute = PluginsPluginIdOptionsImport.update({
  id: '/plugins/$pluginId/options',
  path: '/plugins/$pluginId/options',
  getParentRoute: () => rootRoute,
} as any)

const PluginsPluginIdPlaylistsIndexRoute =
  PluginsPluginIdPlaylistsIndexImport.update({
    id: '/plugins/$pluginId/playlists/',
    path: '/plugins/$pluginId/playlists/',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdChannelsIndexRoute =
  PluginsPluginIdChannelsIndexImport.update({
    id: '/plugins/$pluginId/channels/',
    path: '/plugins/$pluginId/channels/',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdVideosApiIdRoute = PluginsPluginIdVideosApiIdImport.update(
  {
    id: '/plugins/$pluginId/videos/$apiId',
    path: '/plugins/$pluginId/videos/$apiId',
    getParentRoute: () => rootRoute,
  } as any,
)

const PluginsPluginIdPlaylistsApiIdRoute =
  PluginsPluginIdPlaylistsApiIdImport.update({
    id: '/plugins/$pluginId/playlists/$apiId',
    path: '/plugins/$pluginId/playlists/$apiId',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdChannelsApiIdIndexRoute =
  PluginsPluginIdChannelsApiIdIndexImport.update({
    id: '/plugins/$pluginId/channels/$apiId/',
    path: '/plugins/$pluginId/channels/$apiId/',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdChannelsApiIdLiveRoute =
  PluginsPluginIdChannelsApiIdLiveImport.update({
    id: '/plugins/$pluginId/channels/$apiId/live',
    path: '/plugins/$pluginId/channels/$apiId/live',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateImport
      parentRoute: typeof rootRoute
    }
    '/plugininstall': {
      id: '/plugininstall'
      path: '/plugininstall'
      fullPath: '/plugininstall'
      preLoaderRoute: typeof PlugininstallImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/favorites/channels': {
      id: '/favorites/channels'
      path: '/channels'
      fullPath: '/favorites/channels'
      preLoaderRoute: typeof FavoritesChannelsImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/favorites/playlists': {
      id: '/favorites/playlists'
      path: '/playlists'
      fullPath: '/favorites/playlists'
      preLoaderRoute: typeof FavoritesPlaylistsImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/favorites/videos': {
      id: '/favorites/videos'
      path: '/videos'
      fullPath: '/favorites/videos'
      preLoaderRoute: typeof FavoritesVideosImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdImport
      parentRoute: typeof rootRoute
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/options': {
      id: '/plugins/$pluginId/options'
      path: '/plugins/$pluginId/options'
      fullPath: '/plugins/$pluginId/options'
      preLoaderRoute: typeof PluginsPluginIdOptionsImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/': {
      id: '/plugins/$pluginId/'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/playlists/$apiId': {
      id: '/plugins/$pluginId/playlists/$apiId'
      path: '/plugins/$pluginId/playlists/$apiId'
      fullPath: '/plugins/$pluginId/playlists/$apiId'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsApiIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/videos/$apiId': {
      id: '/plugins/$pluginId/videos/$apiId'
      path: '/plugins/$pluginId/videos/$apiId'
      fullPath: '/plugins/$pluginId/videos/$apiId'
      preLoaderRoute: typeof PluginsPluginIdVideosApiIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/channels/': {
      id: '/plugins/$pluginId/channels/'
      path: '/plugins/$pluginId/channels'
      fullPath: '/plugins/$pluginId/channels'
      preLoaderRoute: typeof PluginsPluginIdChannelsIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/playlists/': {
      id: '/plugins/$pluginId/playlists/'
      path: '/plugins/$pluginId/playlists'
      fullPath: '/plugins/$pluginId/playlists'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/channels/$apiId/live': {
      id: '/plugins/$pluginId/channels/$apiId/live'
      path: '/plugins/$pluginId/channels/$apiId/live'
      fullPath: '/plugins/$pluginId/channels/$apiId/live'
      preLoaderRoute: typeof PluginsPluginIdChannelsApiIdLiveImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/channels/$apiId/': {
      id: '/plugins/$pluginId/channels/$apiId/'
      path: '/plugins/$pluginId/channels/$apiId'
      fullPath: '/plugins/$pluginId/channels/$apiId'
      preLoaderRoute: typeof PluginsPluginIdChannelsApiIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FavoritesRouteRouteChildren {
  FavoritesChannelsRoute: typeof FavoritesChannelsRoute
  FavoritesPlaylistsRoute: typeof FavoritesPlaylistsRoute
  FavoritesVideosRoute: typeof FavoritesVideosRoute
}

const FavoritesRouteRouteChildren: FavoritesRouteRouteChildren = {
  FavoritesChannelsRoute: FavoritesChannelsRoute,
  FavoritesPlaylistsRoute: FavoritesPlaylistsRoute,
  FavoritesVideosRoute: FavoritesVideosRoute,
}

const FavoritesRouteRouteWithChildren = FavoritesRouteRoute._addFileChildren(
  FavoritesRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/channels': typeof FavoritesChannelsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/videos': typeof FavoritesVideosRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/videos/$apiId': typeof PluginsPluginIdVideosApiIdRoute
  '/plugins/$pluginId/channels': typeof PluginsPluginIdChannelsIndexRoute
  '/plugins/$pluginId/playlists': typeof PluginsPluginIdPlaylistsIndexRoute
  '/plugins/$pluginId/channels/$apiId/live': typeof PluginsPluginIdChannelsApiIdLiveRoute
  '/plugins/$pluginId/channels/$apiId': typeof PluginsPluginIdChannelsApiIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/channels': typeof FavoritesChannelsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/videos': typeof FavoritesVideosRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/videos/$apiId': typeof PluginsPluginIdVideosApiIdRoute
  '/plugins/$pluginId/channels': typeof PluginsPluginIdChannelsIndexRoute
  '/plugins/$pluginId/playlists': typeof PluginsPluginIdPlaylistsIndexRoute
  '/plugins/$pluginId/channels/$apiId/live': typeof PluginsPluginIdChannelsApiIdLiveRoute
  '/plugins/$pluginId/channels/$apiId': typeof PluginsPluginIdChannelsApiIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/channels': typeof FavoritesChannelsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/videos': typeof FavoritesVideosRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/videos/$apiId': typeof PluginsPluginIdVideosApiIdRoute
  '/plugins/$pluginId/channels/': typeof PluginsPluginIdChannelsIndexRoute
  '/plugins/$pluginId/playlists/': typeof PluginsPluginIdPlaylistsIndexRoute
  '/plugins/$pluginId/channels/$apiId/live': typeof PluginsPluginIdChannelsApiIdLiveRoute
  '/plugins/$pluginId/channels/$apiId/': typeof PluginsPluginIdChannelsApiIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/channels'
    | '/favorites/playlists'
    | '/favorites/videos'
    | '/playlists/$playlistId'
    | '/playlists'
    | '/plugins'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/videos/$apiId'
    | '/plugins/$pluginId/channels'
    | '/plugins/$pluginId/playlists'
    | '/plugins/$pluginId/channels/$apiId/live'
    | '/plugins/$pluginId/channels/$apiId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/channels'
    | '/favorites/playlists'
    | '/favorites/videos'
    | '/playlists/$playlistId'
    | '/playlists'
    | '/plugins'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/videos/$apiId'
    | '/plugins/$pluginId/channels'
    | '/plugins/$pluginId/playlists'
    | '/plugins/$pluginId/channels/$apiId/live'
    | '/plugins/$pluginId/channels/$apiId'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/channels'
    | '/favorites/playlists'
    | '/favorites/videos'
    | '/playlists/$playlistId'
    | '/playlists/'
    | '/plugins/'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId/'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/videos/$apiId'
    | '/plugins/$pluginId/channels/'
    | '/plugins/$pluginId/playlists/'
    | '/plugins/$pluginId/channels/$apiId/live'
    | '/plugins/$pluginId/channels/$apiId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRouteRoute: typeof FavoritesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  PlugininstallRoute: typeof PlugininstallRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsPluginIdOptionsRoute: typeof PluginsPluginIdOptionsRoute
  PluginsPluginIdIndexRoute: typeof PluginsPluginIdIndexRoute
  PluginsPluginIdPlaylistsApiIdRoute: typeof PluginsPluginIdPlaylistsApiIdRoute
  PluginsPluginIdVideosApiIdRoute: typeof PluginsPluginIdVideosApiIdRoute
  PluginsPluginIdChannelsIndexRoute: typeof PluginsPluginIdChannelsIndexRoute
  PluginsPluginIdPlaylistsIndexRoute: typeof PluginsPluginIdPlaylistsIndexRoute
  PluginsPluginIdChannelsApiIdLiveRoute: typeof PluginsPluginIdChannelsApiIdLiveRoute
  PluginsPluginIdChannelsApiIdIndexRoute: typeof PluginsPluginIdChannelsApiIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRouteRoute: FavoritesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  PlugininstallRoute: PlugininstallRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsPluginIdOptionsRoute: PluginsPluginIdOptionsRoute,
  PluginsPluginIdIndexRoute: PluginsPluginIdIndexRoute,
  PluginsPluginIdPlaylistsApiIdRoute: PluginsPluginIdPlaylistsApiIdRoute,
  PluginsPluginIdVideosApiIdRoute: PluginsPluginIdVideosApiIdRoute,
  PluginsPluginIdChannelsIndexRoute: PluginsPluginIdChannelsIndexRoute,
  PluginsPluginIdPlaylistsIndexRoute: PluginsPluginIdPlaylistsIndexRoute,
  PluginsPluginIdChannelsApiIdLiveRoute: PluginsPluginIdChannelsApiIdLiveRoute,
  PluginsPluginIdChannelsApiIdIndexRoute:
    PluginsPluginIdChannelsApiIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favorites",
        "/about",
        "/donate",
        "/plugininstall",
        "/privacy",
        "/search",
        "/settings",
        "/playlists/$playlistId",
        "/playlists/",
        "/plugins/",
        "/plugins/$pluginId/options",
        "/plugins/$pluginId/",
        "/plugins/$pluginId/playlists/$apiId",
        "/plugins/$pluginId/videos/$apiId",
        "/plugins/$pluginId/channels/",
        "/plugins/$pluginId/playlists/",
        "/plugins/$pluginId/channels/$apiId/live",
        "/plugins/$pluginId/channels/$apiId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/favorites": {
      "filePath": "favorites/route.tsx",
      "children": [
        "/favorites/channels",
        "/favorites/playlists",
        "/favorites/videos"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/donate": {
      "filePath": "donate.tsx"
    },
    "/plugininstall": {
      "filePath": "plugininstall.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/favorites/channels": {
      "filePath": "favorites/channels.tsx",
      "parent": "/favorites"
    },
    "/favorites/playlists": {
      "filePath": "favorites/playlists.tsx",
      "parent": "/favorites"
    },
    "/favorites/videos": {
      "filePath": "favorites/videos.tsx",
      "parent": "/favorites"
    },
    "/playlists/$playlistId": {
      "filePath": "playlists.$playlistId.tsx"
    },
    "/playlists/": {
      "filePath": "playlists.index.tsx"
    },
    "/plugins/": {
      "filePath": "plugins.index.tsx"
    },
    "/plugins/$pluginId/options": {
      "filePath": "plugins/$pluginId/options.tsx"
    },
    "/plugins/$pluginId/": {
      "filePath": "plugins/$pluginId.index.tsx"
    },
    "/plugins/$pluginId/playlists/$apiId": {
      "filePath": "plugins/$pluginId/playlists.$apiId.tsx"
    },
    "/plugins/$pluginId/videos/$apiId": {
      "filePath": "plugins/$pluginId/videos.$apiId.tsx"
    },
    "/plugins/$pluginId/channels/": {
      "filePath": "plugins/$pluginId/channels.index.tsx"
    },
    "/plugins/$pluginId/playlists/": {
      "filePath": "plugins/$pluginId/playlists.index.tsx"
    },
    "/plugins/$pluginId/channels/$apiId/live": {
      "filePath": "plugins/$pluginId/channels.$apiId.live.tsx"
    },
    "/plugins/$pluginId/channels/$apiId/": {
      "filePath": "plugins/$pluginId/channels.$apiId.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
